name: shared_analyzer
description: Shared analyzer configs
version: 1.0.0
publish_to: none
homepage: https://github.com/telchardev/armature
issue_tracker: https://github.com/telchardev/armature/issues

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  lints: ^6.0.0
  flutter_lints: ^6.0.0